spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:user-center}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${MYSQL-USER:root}
    password: ${MYSQL-PWD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ocp.**.**.entity
  global-config:
    db-config:
      id-type: auto
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ocp:
  swagger:
    enabled: true
    title: 用户中心
    description: 用户中心接口文档
    version: 1.0
    base-package: com.ocp.server.user.controller
  cache-manager:
    configs:
      - key: menu
        second: 300
      - key: user
        second: 1800
  #多租户配置
  tenant:
    enable: true
    ignoreTables:
      - sys_user
      - sys_role_user
      - sys_role_menu
    ignoreSqls:
      # 用户关联角色时，显示所有角色
      - com.ocp.server.user.mapper.SysRoleMapper.findAll
      # 用户列表显示用户所关联的所有角色
      - com.ocp.server.user.mapper.SysUserRoleMapper.findRolesByUserIds